# Generated by Django 6.0.1 on 2026-02-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='summary',
            field=models.TextField(default='Memory Summary'),
            preserve_default=False,
        ),
    ]
