# Generated by Django 6.0.1 on 2026-02-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_memory_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='summary',
        ),
    ]
