# Generated by Django 6.0.1 on 2026-01-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_session_options_alter_session_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['session', '-created_at']},
        ),
    ]
