# Generated by Django 6.0.1 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_memory_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="access_clock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="memory",
            name="planner_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="bullet_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="context_scope_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="episodic_access_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="episodic_last_access",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="episodic_strength",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="learner_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="procedural_access_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="procedural_last_access",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="procedural_strength",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="semantic_access_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="semantic_last_access",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="semantic_strength",
            field=models.FloatField(default=0.0),
        ),
    ]
