# Generated by Django 6.0.1 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_ace_memory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="generation_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="generation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
