# Generated by Django 6.0.1 on 2026-03-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_ace_memory_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorybullet',
            name='content_hash',
        ),
    ]
