# Generated by Django 6.0.1 on 2026-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_memorybullet_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorybullet',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
