# Generated by Django 6.0.1 on 2026-03-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_session_generation_lock'),
        ('chat', '0006_memorybullet_content_hash'),
    ]

    operations = [
    ]
