# Generated by Django 6.0.1 on 2026-04-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_merge_20260311_1225"),
        ("users", "0006_userprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorybullet",
            name="embedding_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="is_skill",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="skill_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="memorybullet",
            name="skill_group",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/agents/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=1024)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="sender_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.agent",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="chat.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "notification_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Agent Response"),
                            (2, "Skill Generated"),
                            (3, "Memory Threshold"),
                            (4, "System Alert"),
                        ]
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "related_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="chat.agent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.session",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_agent_user_id_a295ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_auditl_user_id_5d6950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="chat_auditl_event_t_675ac6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="chat_notifi_user_id_028bb1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together={("session", "agent")},
        ),
    ]
