# Generated by Django 6.0.1 on 2026-04-07 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_memorybullet_embedding_json_memorybullet_is_skill_and_more"),
        ("users", "0006_userprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="access_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="session",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SessionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chat.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("session", "user")},
            },
        ),
    ]
