# Generated by Django 6.0.1 on 2026-04-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_add_document_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="chat.agent",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="agent_documents/"),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
