# Generated by Django 6.0.1 on 2026-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_add_agent_file_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorybullet",
            name="ttl_days",
            field=models.IntegerField(default=30),
        ),
    ]
