# Generated by Django 6.0.1 on 2026-04-09 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_document_file_storage_and_ttl"),
        ("users", "0006_userprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(db_index=True, default="chat", max_length=32),
                ),
                (
                    "model_name",
                    models.CharField(default="gemini-3-flash-preview", max_length=64),
                ),
                ("pipeline", models.CharField(default="gemini_direct", max_length=32)),
                ("status", models.CharField(default="success", max_length=16)),
                ("latency_ms", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("estimated_cost_usd", models.FloatField(default=0.0)),
                (
                    "error_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="chat.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_logs",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chat_reques_user_id_df05ee_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-created_at"],
                        name="chat_reques_model_n_8c1876_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="chat_reques_status_1fb5f6_idx",
                    ),
                ],
            },
        ),
    ]
