# Generated by Django 6.0.1 on 2026-04-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_add_memory_vote_model"),
        ("users", "0006_userprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("template", "Template"),
                            ("custom", "Custom"),
                            ("generated", "Generated from memories"),
                        ],
                        default="template",
                        max_length=20,
                    ),
                ),
                ("source_bullet_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "slug"), name="unique_skill_per_user"
                    )
                ],
            },
        ),
    ]
