# Generated by Django 6.0.1 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_add_skill_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_agent_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
