# Generated by Django 6.0.1 on 2026-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_add_sender_agent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("applied", "applied"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="chat_outbox_status_eac363_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="chat_outbox_entity__d89691_idx",
                    ),
                ],
            },
        ),
    ]
