from django.urls import path

from . import api, views

app_name = "chat"

page_urlpatterns = [
    path("memory/", views.memory_list_view, name="memory"),
    path("c/<str:session_id>/", views.conversation_messages_view, name="conversation_detail"),
    path("c/<str:session_id>/lock-status/", views.conversation_lock_status_view, name="conversation_lock_status"),
    path("c/<str:session_id>/lock-wait/", views.conversation_wait_for_unlock_view, name="conversation_lock_wait"),
    path("c/<str:session_id>/stream/", views.conversation_stream_subscribe_view, name="conversation_stream_subscribe"),
    path("c/<str:session_id>/rename/", views.session_rename_view, name="session_rename"),
    path("c/<str:session_id>/delete/", views.session_delete_view, name="session_delete"),
    path("c/<str:session_id>/typing/", views.typing_view, name="typing"),
    path("c/<str:session_id>/stop-typing/", views.stop_typing_view, name="stop_typing"),
    path("c/<str:session_id>/upload/", views.conversation_upload_view, name="conversation_upload"),
    path("c/<str:session_id>/messages/<str:message_id>/edit/", views.message_edit_view, name="message_edit"),
    path("c/<str:session_id>/messages/<str:message_id>/resend/", views.message_resend_view, name="message_resend"),
    path("m/<str:memory_id>/", views.memory_bullets_view, name="memory_detail"),
    path("analytics/", views.analytics_view, name="analytics"),
    path("analytics/memory-type.png", views.memory_type_chart_png, name="memory_type_chart"),
    path("analytics/memory-strength.png", views.memory_strength_chart_png, name="memory_strength_chart"),
    path("analytics/activity.png", views.activity_chart_png, name="activity_chart"),
    path("analytics/export/sessions/", views.export_sessions_report, name="export_sessions_report"),
    path("analytics/export/memory-bullets/", views.export_memory_bullets_report, name="export_memory_bullets_report"),
    path("analytics/latency-over-time.png", views.latency_over_time_chart_png, name="latency_over_time_chart"),
    path("analytics/latency-by-model.png", views.latency_by_model_chart_png, name="latency_by_model_chart"),
    path("analytics/error-rate.png", views.error_rate_chart_png, name="error_rate_chart"),
    path("analytics/daily-cost.png", views.daily_cost_chart_png, name="daily_cost_chart"),
    path("analytics/token-usage.png", views.token_usage_chart_png, name="token_usage_chart"),
    path("analytics/cost-by-model.png", views.cost_by_model_chart_png, name="cost_by_model_chart"),
    path("analytics/export/request-log/", views.export_request_log_report, name="export_request_log_report"),
    path(
        "charts/active-users/",
        views.vega_daily_users_chart_view,
        name="charts_active_users",
    ),
    path(
        "charts/messages/",
        views.vega_daily_messages_chart_view,
        name="charts_messages",
    ),
    path("agents/my/", views.my_agent_redirect_view, name="my_agent"),
    path("agents/marketplace/", views.agent_marketplace_view, name="agent_marketplace"),
    path("agents/marketplace/<str:template_id>/start-chat/", views.agent_start_chat_view, name="agent_start_chat"),
    path("agents/marketplace/<str:template_id>/", views.agent_marketplace_detail_view, name="agent_marketplace_detail"),
    path("agents/<str:agent_id>/", views.agent_detail_view, name="agent_detail"),
    path("agents/<str:agent_id>/delete/", views.agent_delete_view, name="agent_delete"),
    path("agents/<str:agent_id>/settings/", views.agent_settings_view, name="agent_settings"),
    path("agents/<str:agent_id>/skills/", views.agent_skills_view, name="agent_skills"),
    path("agents/<str:agent_id>/files/", views.agent_files_view, name="agent_files"),
    path("agents/<str:agent_id>/files/<str:document_id>/delete/", views.agent_file_delete_view, name="agent_file_delete"),
    path("agents/<str:agent_id>/files/<str:document_id>/description/", views.agent_file_update_description_view, name="agent_file_update_description"),
    path("agents/<str:agent_id>/memory/", views.agent_memory_view, name="agent_memory"),
    path("memory/<str:bullet_id>/vote/", views.memory_vote_view, name="memory_vote"),
    path("skills/<str:bullet_id>/toggle/", views.skill_toggle_view, name="skill_toggle"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("activity/", views.activity_log_view, name="activity_log"),
    path("settings/admin/", views.admin_settings_view, name="admin_settings"),
    path("documents/", views.document_hub_view, name="document_hub"),
    path("document/upload/", views.document_upload_view, name="document_upload"),
    path("groups/", views.group_list_view, name="group_list"),
    path("new/", views.new_chat_view, name="new_chat"),
    path("groups/create/", views.group_create_view, name="group_create"),
    path("groups/join/", views.group_join_view, name="group_join"),
    path("groups/<str:session_id>/leave/", views.group_leave_view, name="group_leave"),
    path("groups/<str:session_id>/settings/", views.group_settings_view, name="group_settings"),
    path("skills/marketplace/", views.skill_marketplace_view, name="skill_marketplace"),
    path("skills/marketplace/<str:skill_id>/", views.skill_marketplace_detail_view, name="skill_marketplace_detail"),
    path("skills/marketplace/<str:skill_id>/install/", views.skill_install_view, name="skill_install"),
    path("notifications/mark-read/<str:notification_id>/", views.notification_mark_read_view, name="notification_mark_read"),
    path("notifications/mark-all-read/", views.notification_mark_all_read_view, name="notification_mark_all_read"),
]

api_urlpatterns = [
    path("api/memories/", api.api_memory_bullets, name="api_memories"),
    path("api/analytics/", api.api_analytics_summary, name="api_analytics"),
    path("api/sessions/", api.SessionAPIView.as_view(), name="api_sessions"),
    path("api/sessions/<str:session_id>/messages/", api.MessageAPIView.as_view(), name="api_messages"),
    path("api/active-users/", api.api_public_daily_active_users, name="api_active_users"),
    path(
        "api/active-users/holidays/",
        api.api_public_daily_active_users_with_holidays,
        name="api_active_users_holidays",
    ),
    path("api/pusher/auth/", views.pusher_auth_view, name="pusher_auth"),
    path("api/agents/", api.api_agents, name="api_agents"),
    path("api/agents/<str:agent_id>/skills/", api.api_agent_skills, name="api_agent_skills"),
    path("api/notifications/", api.api_notifications, name="api_notifications"),
    path("api/activity/", api.api_activity_feed, name="api_activity_feed"),
    path("api/semantic-search/", api.api_semantic_search, name="api_semantic_search"),
]

urlpatterns = page_urlpatterns + api_urlpatterns
