# Generated by Django 6.0.1 on 2026-02-25 03:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('chat', '0003_remove_memory_summary'),
        ('users', '0004_user_uuid_not_null_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users_user',
        ),
    ]
